// response-loss-v1: request reaches Next and commits; only delivery to the browser
// fails. The evaluator knows the authoritative outcome; the missing ack alone does not.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BrowserSession, Recorder, browserPrerequisites, makeUpstreamController, pollUntil, setAppLocale } from "./chat-browser-checks";
import { projectFixture as f } from "./chat-project-followup-checks";
import { assertDeleteOnly } from "./chat-project-delete-checks";

export const LOSS_GATES = ["browser.login-dark-en-de", "browser.cancel-state", "browser.pre-dispatch-control", "browser.pre-dispatch-consumer", "browser.pre-dispatch-settles", "browser.success-control", "browser.success-consumer", "browser.success-settles",
  ...["regenerate", "edit"].flatMap(k => [`browser.${k}-forwarded-commit`, `browser.${k}-lost-response`, `browser.${k}-reconciliation`, `browser.${k}-late-memory`, `browser.${k}-direct-consumer`, `browser.${k}-settles`]),
  "browser.operation-outcomes", "browser.no-page-errors", "browser.no-blocked-requests", "browser.responses-drained"];
const instructions = "Synthetic response-loss project instructions.";
function state(ctx: any) {
  const require = createRequire(join(ctx.appDir, "package.json")), Database = require("better-sqlite3"), db = new Database(join(ctx.dataDir, "cortex-chat.db"), { readonly: true, fileMustExist: true });
  try { return { projects: db.prepare("SELECT * FROM projects ORDER BY id").all(), shares: db.prepare("SELECT * FROM project_shares ORDER BY id").all(), sessions: db.prepare("SELECT * FROM chat_sessions ORDER BY id").all(), messages: db.prepare("SELECT * FROM chat_messages ORDER BY id").all() }; } finally { db.close(); }
}
async function fixture(ctx: any, owner: string, member: string, tag: string) {
  const p = (await f.json(ctx, "/api/me/projects", owner, "POST", { name: `${tag} project`, instructions })).project; await f.json(ctx, `/api/me/projects/${p.id}/shares`, owner, "PUT", { shares: [{ userId: ctx.users.member.id }] });
  const create = async (cookie: string, title: string) => { const id = (await f.json(ctx, "/api/me/chats", cookie, "POST", { title, projectId: p.id, assistantId: ctx.ids.soul })).id, pre = f.blob(`${title}-pre`), base = f.pair(`fx-loss-${title}-${ctx.label}`, title).map(m => m.role === "assistant" ? { ...m, feedback: "up", thinking: ["Retained reasoning"], sources: [{ document_id: "fx-loss-source", chunk_id: "fx-loss-chunk", sid: "fx-loss-stable-sid", content: "Retained source", score: 0.42, metadata: { filename: "response-loss-fixture.md" } }] } : m); await f.patch(ctx, cookie, id, base, pre); await f.json(ctx, `/api/me/chats/${id}`, cookie, "PATCH", { pinned: true }); return { id, title, pre, base }; };
  return { p, own: await create(owner, `${tag} own chat`), peer: await create(member, `${tag} peer chat`) };
}
export async function runLossBrowser(ctx: any) {
  const rec = new Recorder(join(ctx.workDir, "logs")), tool = browserPrerequisites(); assert.deepEqual(tool.problems, []);
  const require = createRequire(join(ctx.appDir, "package.json")), pw = require(join(tool.pwPath, "index.js")), owner = new BrowserSession(pw, tool.chromiumPath, ctx.baseUrl, rec), c = makeUpstreamController(ctx);
  for (const [path, name] of [["src/app/page.tsx", "page.tsx"], ["src/lib/projects-client.ts", "projects-client.ts"], ["src/app/api/me/projects/[id]/route.ts", "delete-route.ts"]]) copyFileSync(join(ctx.appDir, path), join(rec.dir, name)); writeFileSync(join(rec.dir, "tooling.json"), JSON.stringify({ ...tool, version: JSON.parse(readFileSync(join(tool.pwPath, "package.json"), "utf8")).version, tmpdir: process.env.TMPDIR, install: false }, null, 2));
  const writes: any[] = [], acks: any[] = [], failures: any[] = [], asks: any[] = [], reads: any[] = [], lists: any[] = [], dialogs: any[] = [], faults: any[] = [], barriers: any[] = [], consoleErrors: any[] = [];
  const g = (id: string, fn: () => Promise<any>) => f.gate(ctx, `browser.${id}`, fn), log = () => readFileSync(join(ctx.workDir, "logs", "app-dev.log"), "utf8");
  const tracked = (path: string, method: string) => method === "DELETE" && /^\/api\/me\/projects\/[^/]+$/.test(path) || method === "PATCH" && /^\/api\/me\/chats\/[^/]+$/.test(path);
  try {
    await owner.start(); owner.page.on("console", (m: any) => { if (m.type() === "error") consoleErrors.push({ text: m.text(), location: m.location(), at: Date.now() }); });
    owner.context.on("request", (r: any) => { const path = new URL(r.url()).pathname, method = r.method(); if (tracked(path, method)) writes.push({ path, method, body: r.postDataJSON(), at: Date.now() }); if (path === "/api/ask/stream") asks.push({ id: r.headers()["x-request-id"], body: r.postDataJSON(), at: Date.now() }); if (method === "GET" && /^\/api\/me\/chats\/[^/]+$/.test(path)) reads.push({ path, at: Date.now() }); });
    owner.context.on("requestfailed", (r: any) => { const path = new URL(r.url()).pathname; if (tracked(path, r.method())) failures.push({ path, method: r.method(), error: r.failure()?.errorText, at: Date.now() }); });
    owner.context.on("response", (r: any) => { const path = new URL(r.url()).pathname, method = r.request().method(); if (tracked(path, method)) acks.push({ path, method, body: r.request().postDataJSON(), status: r.status(), at: Date.now() }); if (method === "GET" && path === "/api/me/projects") lists.push({ path, status: r.status(), at: Date.now() }); });
    await owner.login(ctx, ctx.users.owner.email, ctx.users.owner.password); const member = await f.login(ctx, "member");
    const sidebar = async () => { if (!await owner.drawer().isVisible()) { await owner.page.locator('button[aria-label="Toggle sidebar"], button[aria-label="Seitenleiste umschalten"]').click(); await owner.drawer().waitFor({ state: "visible", timeout: 30000 }); } };
    const closeSidebar = async () => { if (await owner.drawer().isVisible()) await owner.drawer().locator("button").first().click(); };
    const frames = () => owner.page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
    const open = async (chat: any) => { await owner.page.goto(`${ctx.baseUrl}/?chat=${chat.id}`, { waitUntil: "domcontentloaded" }); await owner.waitForComposer(); assert.ok(await f.visible(owner, chat.base[1].content)); };
    const native = async (p: any, decision: "accept" | "dismiss", locale: "en" | "de" = "en") => { await sidebar(); const row = owner.drawer().getByText(p.name, { exact: true }).locator(".."); await row.hover(); const handled = new Promise<void>((resolve, reject) => owner.page.once("dialog", async (d: any) => { try { assert.equal(d.type(), "confirm"); assert.equal(d.message(), locale === "en" ? "Delete this project? Chats are kept and move back to their authors' chat lists." : "Dieses Projekt löschen? Chats bleiben erhalten und wandern zurück in die Chat-Listen ihrer Autoren."); dialogs.push({ type: d.type(), text: d.message(), project: p.id, decision, locale }); await d[decision](); resolve(); } catch (e) { await d.dismiss().catch(() => {}); reject(e); } })); await row.locator(`button[title="${locale === "en" ? "Delete project" : "Projekt löschen"}"]`).click(); await handled; };
    const waitActive = async (q: string, count: number) => assert.ok(await pollUntil(() => { const b = asks.filter(a => a.body.question === q), u = ctx.upstream.requests.filter((r: any) => r.body?.question === q); return b.length === count && u.length === count && b.at(-1).id === u.at(-1).id && ctx.upstream.pending.has(u.at(-1).id) && c.held.some(h => h.id === u.at(-1).id); }, 15000));
    const consume = (q: string, chat: any, projectId: string | null, count: number, prefix = chat.base) => { const raw = asks.filter(a => a.body.question === q).at(-1).body, sent = ctx.upstream.requests.filter((r: any) => r.body?.question === q).at(-1).body; assert.equal(raw.session_id, chat.id); assert.equal(raw.project_id, projectId, "reconciled authoritative association, not missing-ack rollback, owns current context"); assert.equal(raw.assistant_id, ctx.ids.soul); assert.deepEqual(raw.conversation_memory, chat.pre); assert.deepEqual(sent.conversation_memory, chat.pre); assert.deepEqual(raw.conversation_history, prefix.map((m: any) => ({ role: m.role, content: m.content }))); assert.equal(reads.length, count); assert.equal(JSON.stringify(sent).includes(instructions), projectId !== null); return { raw, sent }; };
    const intercept = async (p: any, phase: "pre-dispatch" | "post-commit") => { const matcher = `${ctx.baseUrl}/api/me/projects/${p.id}`, row: any = { path: `/api/me/projects/${p.id}`, method: "DELETE", phase, intercepted: false, aborted: false, forwarded: false, release: null }; const handler = async (route: any) => { if (route.request().method() !== "DELETE" || row.intercepted) return route.fallback(); row.intercepted = true; row.at = Date.now(); faults.push(row); if (phase === "post-commit") { const response = await route.fetch(); row.forwarded = true; row.status = response.status(); row.body = await response.json(); row.responseAt = Date.now(); let release!: () => void; const promise = new Promise<void>(r => release = r); row.release = release; await promise; } await route.abort("failed"); row.aborted = true; row.failedAt = Date.now(); }; await owner.context.route(matcher, handler); barriers.push({ row, close: async () => { row.release?.(); await owner.context.unroute(matcher, handler); } }); return row; };
    const canceled = await fixture(ctx, owner.cookie, member, "Cancel loss");
    await g("login-dark-en-de", async () => { assert.equal((await f.json(ctx, "/api/auth/me", owner.cookie)).id, ctx.users.owner.id); assert.equal(await owner.page.evaluate(() => document.documentElement.classList.contains("dark")), true); setAppLocale(ctx.dataDir, "de"); try { await owner.page.reload(); await owner.waitForComposer(); const before = state(ctx), n = writes.length; await native(canceled.p, "dismiss", "de"); assert.deepEqual(state(ctx), before); assert.equal(writes.length, n); await rec.screenshot(owner.page, "loss-dark-de-cancel"); } finally { setAppLocale(ctx.dataDir, "en"); } await owner.page.reload(); await owner.waitForComposer(); return { locales: ["de", "en"] }; });
    await g("cancel-state", async () => { const before = state(ctx), n = writes.length; await native(canceled.p, "dismiss"); assert.deepEqual(state(ctx), before); assert.equal(writes.length, n); return before; });
    const pre = await fixture(ctx, owner.cookie, member, "Known pre-dispatch"); await open(pre.own); const preBefore = state(ctx), preRefresh = lists.length, preFault = await intercept(pre.p, "pre-dispatch"); await native(pre.p, "accept");
    await g("pre-dispatch-control", async () => { assert.ok(await pollUntil(() => preFault.aborted && failures.some(r => r.path === preFault.path), 10000)); assert.equal(preFault.forwarded, false); assert.deepEqual(state(ctx), preBefore); assert.equal(log().includes(`DELETE ${preFault.path} `), false); assert.equal(acks.some(a => a.path === preFault.path), false); assert.ok(await pollUntil(() => lists.length > preRefresh, 10000)); await closeSidebar(); await frames(); return { before: preBefore, after: state(ctx), fault: { ...preFault, release: undefined } }; });
    const pq = pre.own.base[0].content, pn = reads.length; c.plans.set(pq, [{ frames: [{ content: "Pre-dispatch retained redo" }], holdOnly: true }]); await owner.clickRegenerate(); await waitActive(pq, 1); await g("pre-dispatch-consumer", async () => consume(pq, pre.own, pre.p.id, pn, [])); c.release(pq, [{ memory_update: f.blob("pre-dispatch-final") }, f.done]); await g("pre-dispatch-settles", () => f.durable(owner, ctx, pre.own.id, f.blob("pre-dispatch-final"), "Pre-dispatch retained redo"));
    const success = await fixture(ctx, owner.cookie, member, "Acknowledged success"); await open(success.own); await g("success-control", async () => { const before = state(ctx); await native(success.p, "accept"); assert.ok(await pollUntil(() => acks.some(a => a.path === `/api/me/projects/${success.p.id}` && a.status === 200), 10000)); assertDeleteOnly(before, state(ctx), success.p.id); assert.ok(await pollUntil(() => log().includes(`DELETE /api/me/projects/${success.p.id} 200`), 5000)); await closeSidebar(); await frames(); return { before, after: state(ctx), healthyServerLog: true }; });
    const sq = success.own.base[0].content, sn = reads.length; c.plans.set(sq, [{ frames: [{ content: "Success detached redo" }], holdOnly: true }]); await owner.clickRegenerate(); await waitActive(sq, 1); await g("success-consumer", async () => consume(sq, success.own, null, sn, [])); c.release(sq, [{ memory_update: f.blob("success-final") }, f.done]); await g("success-settles", () => f.durable(owner, ctx, success.own.id, f.blob("success-final"), "Success detached redo"));
    for (const kind of ["regenerate", "edit"] as const) {
      const fx = await fixture(ctx, owner.cookie, member, `Lost ${kind}`); await open(fx.own); const q = `loss-${kind}-${ctx.label}`, answer = `${kind} completed origin`, late = f.blob(`${kind}-valid-late`); c.plans.set(q, [{ frames: [{ content: answer }, f.done], holdMemoryBlob: late }, { frames: [{ content: "regenerate reconciled redo" }], holdOnly: true }]); await owner.send(q); await owner.waitAnswerVisible(answer); const origin = (await f.durable(owner, ctx, fx.own.id, fx.own.pre, answer)).http.body.messages; await waitActive(q, 1);
      const before = state(ctx), refreshes = lists.length, fault = await intercept(fx.p, "post-commit"); await native(fx.p, "accept");
      await g(`${kind}-forwarded-commit`, async () => { assert.ok(await pollUntil(() => fault.release && fault.forwarded, 10000)); assert.equal(fault.status, 200); assert.deepEqual(fault.body, { ok: true }); assert.equal(fault.aborted, false); assertDeleteOnly(before, state(ctx), fx.p.id); assert.equal(acks.some(a => a.path === fault.path), false); assert.ok(await pollUntil(() => log().includes(`DELETE ${fault.path} 200`), 5000)); return { before, committed: state(ctx), genuineResponse: { status: fault.status, body: fault.body }, browserAcknowledgment: "not delivered" }; });
      fault.release(); await g(`${kind}-lost-response`, async () => { assert.ok(await pollUntil(() => fault.aborted && failures.some(r => r.path === fault.path), 10000)); const failed = failures.find(r => r.path === fault.path); assert.equal(failed.error, "net::ERR_FAILED"); assert.equal(failed.method, "DELETE"); assert.equal(acks.some(a => a.path === fault.path), false); assertDeleteOnly(before, state(ctx), fx.p.id); return { failed, committed: state(ctx), fault: { ...fault, release: undefined }, note: "evaluator knows commit; missing acknowledgment alone cannot establish caller outcome" }; });
      await g(`${kind}-reconciliation`, async () => { assert.ok(await pollUntil(() => lists.length > refreshes && lists.at(-1).status === 200, 10000)); await sidebar(); assert.ok(await pollUntil(async () => await owner.drawer().getByText(fx.p.name, { exact: true }).count() === 0 && await owner.drawer().getByText(fx.own.title, { exact: true }).count() === 1, 10000)); assert.equal(await owner.drawer().getByText(fx.peer.title, { exact: true }).count(), 0); assert.equal(new URL(owner.page.url()).searchParams.get("chat"), fx.own.id); const got = await f.json(ctx, `/api/me/chats/${fx.own.id}`, owner.cookie); assert.equal(got.projectId, null); await closeSidebar(); await frames(); return { selected: fx.own.id, authoritativeOwnRead: got, listReconciliation: "actual page refresh; no injected chat state" }; });
      c.release(q, [{ memory_update: late }]); await g(`${kind}-late-memory`, async () => { const got = await f.durable(owner, ctx, fx.own.id, late, answer); assert.equal(got.http.body.projectId, null); assert.deepEqual(f.projection(got.http.body.messages), f.projection(origin)); return got; });
      const question = kind === "edit" ? `loss-edited-${ctx.label}` : q, n = reads.length; if (kind === "edit") { c.plans.set(question, [{ frames: [{ content: "edit reconciled redo" }], holdOnly: true }]); await owner.editLastMessage(q, question); } else await owner.clickRegenerate(); await waitActive(question, kind === "edit" ? 1 : 2);
      await g(`${kind}-direct-consumer`, async () => consume(question, fx.own, null, n)); c.release(question, [{ memory_update: f.blob(`${kind}-redo-final`) }, f.done]); await g(`${kind}-settles`, async () => { const got = await f.durable(owner, ctx, fx.own.id, f.blob(`${kind}-redo-final`), `${kind} reconciled redo`); assert.equal(got.http.body.projectId, null); assert.equal(got.http.body.assistantId, ctx.ids.soul); await rec.screenshot(owner.page, `loss-${kind}-settled`); return got; });
    }
    await pollUntil(() => writes.length === acks.length + failures.length, 10000); await g("operation-outcomes", async () => { assert.equal(faults.length, 3); assert.equal(failures.length, 3); assert.equal(writes.length, acks.length + failures.length); assert.ok(acks.every(a => a.status === 200)); for (const fault of faults) { assert.equal(writes.filter(w => w.method === "DELETE" && w.path === fault.path).length, 1, "a missing acknowledgment must not automatically replay DELETE"); assert.equal(failures.filter(f => f.path === fault.path && f.error === "net::ERR_FAILED").length, 1); assert.equal(acks.some(a => a.path === fault.path), false); assert.equal(fault.forwarded, fault.phase === "post-commit"); assert.equal(fault.aborted, true); if (fault.forwarded) assert.ok(log().includes(`DELETE ${fault.path} 200`)); else assert.equal(log().includes(`DELETE ${fault.path} `), false); } return { writes, acknowledgments: acks, expectedTransportFailures: failures, faultPhases: faults.map(({ release, ...r }) => r), automaticDeleteReplay: false }; });
  } finally {
    for (const b of barriers) await b.close(); ctx.check("browser.no-page-errors", !owner.pageErrors.length, owner.pageErrors); ctx.check("browser.no-blocked-requests", !owner.blocked.length, owner.blocked); ctx.check("browser.responses-drained", !c.held.length && !c.unmatched.length && !ctx.upstream.pending.size && barriers.every(b => b.row.aborted), { held: c.held, unmatched: c.unmatched });
    writeFileSync(join(rec.dir, "response-loss-observations.json"), JSON.stringify({ writes, acknowledgments: acks, failures, asks, reads, projectListResponses: lists, dialogs, faults: faults.map(({ release, ...r }) => r), consoleErrors, observations: rec.observations }, null, 2)); await owner.close();
  }
}
