// remote-delete-v1: retained author work and direct consumers; fresh admission is
// separate from observed connect-time subscriptions and admitted ask authority.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BrowserSession, Recorder, browserPrerequisites, makeUpstreamController, pollUntil, setAppLocale } from "./chat-browser-checks";
import { projectFixture as f } from "./chat-project-followup-checks";
import { assertDeleteOnly } from "./chat-project-delete-checks";

export const REMOTE_HTTP_GATES = ["http.shared-control", "http.admitted-ask-control", "http.exact-detach", "http.fresh-admission", "http.open-feed-observation", "http.admitted-ask-completes", "http.non-author-late-save-rejected", "http.fresh-general-ask-scope"];
export const REMOTE_BROWSER_GATES = ["browser.logins-dark-en-de", "browser.cancel-control", "browser.healthy-consumer", "browser.healthy-settles",
  ...["regenerate", "edit"].flatMap(k => [`browser.${k}-origin-control`, `browser.${k}-exact-detach`, `browser.${k}-flat-selected`, `browser.${k}-fresh-admission`, `browser.${k}-late-memory`, `browser.${k}-direct-feedback`, `browser.${k}-direct-snapshot-context`, `browser.${k}-settles`]),
  "browser.non-author-selected-control", "browser.non-author-detach", "browser.non-author-fresh-rejection", "browser.non-author-admitted-completion", "browser.non-author-save-rejection", "browser.operation-outcomes", "browser.no-page-errors", "browser.no-blocked-requests", "browser.responses-drained"];
const instructions = "Synthetic remote-deletion project instructions.";
function state(ctx: any) {
  const require = createRequire(join(ctx.appDir, "package.json")), Database = require("better-sqlite3"), db = new Database(join(ctx.dataDir, "cortex-chat.db"), { readonly: true, fileMustExist: true });
  try { return { projects: db.prepare("SELECT * FROM projects ORDER BY id").all(), shares: db.prepare("SELECT * FROM project_shares ORDER BY id").all(), sessions: db.prepare("SELECT * FROM chat_sessions ORDER BY id").all(), messages: db.prepare("SELECT * FROM chat_messages ORDER BY id").all() }; } finally { db.close(); }
}
async function fixture(ctx: any, owner: string, member: string, tag: string) {
  const p = (await f.json(ctx, "/api/me/projects", owner, "POST", { name: `${tag} project`, instructions, collectionId: "fx-remote-creation-default" })).project;
  await f.json(ctx, `/api/me/projects/${p.id}/shares`, owner, "PUT", { shares: [{ userId: ctx.users.member.id }] });
  const create = async (cookie: string, title: string) => {
    const id = (await f.json(ctx, "/api/me/chats", cookie, "POST", { title, projectId: p.id, assistantId: ctx.ids.soul })).id;
    const base = f.pair(`fx-remote-${title}-${ctx.label}`, title).map(m => m.role === "assistant" ? { ...m, feedback: "up", thinking: ["Preserved reasoning"], sources: [{ document_id: "fx-remote-source", chunk_id: "fx-remote-chunk", content: "Preserved source", score: 0.42, sid: "fx-remote-stable-sid", metadata: { filename: "fixture-remote.md" } }] } : m), pre = f.blob(`${title}-pre`);
    await f.patch(ctx, cookie, id, base, pre); await f.json(ctx, `/api/me/chats/${id}`, cookie, "PATCH", { pinned: true }); return { id, title, base, pre };
  };
  const a = await create(owner, `${tag} owner chat`), b = await create(member, `${tag} member chat`);
  // Preserve mixed message authors as well as each chat's surviving owner.
  a.base = [...a.base, ...f.pair(`fx-remote-peer-${tag}-${ctx.label}`, `${tag} peer prefix`)]; await f.patch(ctx, member, a.id, a.base, a.pre);
  return { p, a, b };
}
async function admission(ctx: any, cookie: string, id: string, allowed: boolean) {
  const read = await ctx.request(`/api/me/chats/${id}`, { cookie }), body = await read.json(); assert.equal(read.status, allowed ? 200 : 404);
  const abort = new AbortController(), feed = await fetch(`${ctx.baseUrl}/api/me/chats/${id}/events`, { headers: { Cookie: cookie }, signal: AbortSignal.any([abort.signal, AbortSignal.timeout(15000)]) });
  try { assert.equal(feed.status, allowed ? 200 : 404); if (allowed) assert.ok(new TextDecoder().decode((await feed.body!.getReader().read()).value).includes(": connected")); else await feed.json(); } finally { abort.abort(); }
  let saveStatus;
  if (!allowed) { const before = state(ctx), save = await ctx.request(`/api/me/chats/${id}`, { cookie, method: "PATCH", body: { messages: [], memory: { forbidden: true } } }); saveStatus = save.status; assert.equal(save.status, 404); await save.json(); assert.deepEqual(state(ctx), before); }
  return { status: read.status, freshFeedStatus: feed.status, saveStatus, body };
}
async function bothAdmissions(ctx: any, owner: string, member: string, fx: any) {
  return { ownerOwn: await admission(ctx, owner, fx.a.id, true), memberOwn: await admission(ctx, member, fx.b.id, true), formerOwner: await admission(ctx, owner, fx.b.id, false), formerMember: await admission(ctx, member, fx.a.id, false) };
}
export async function runRemoteHttp(ctx: any) {
  const owner = await f.login(ctx, "owner"), member = await f.login(ctx, "member"), fx = await fixture(ctx, owner, member, "HTTP remote"), c = makeUpstreamController(ctx);
  const abort = new AbortController(), feed = await fetch(`${ctx.baseUrl}/api/me/chats/${fx.a.id}/events`, { headers: { Cookie: member }, signal: AbortSignal.any([abort.signal, AbortSignal.timeout(90000)]) }), events: string[] = [];
  const reader = feed.body!.getReader(); let stopped = false;
  const pump = (async () => { try { while (!stopped) { const r = await reader.read(); if (r.done) break; events.push(new TextDecoder().decode(r.value)); } } catch (e) { if (!abort.signal.aborted) throw e; } })();
  const q = `admitted-non-author-${ctx.label}`, late = f.blob("http-non-author-late"); let askText: Promise<string> | undefined;
  try {
    await f.gate(ctx, "http.shared-control", async () => { assert.equal(feed.status, 200); assert.ok(await pollUntil(() => events.join("").includes(": connected"), 10000)); const got = await admission(ctx, member, fx.a.id, true); assert.deepEqual(got.body.memory, fx.a.pre); await f.patch(ctx, member, fx.a.id, fx.a.base, fx.a.pre); return { admission: got, connectTimeFeed: events.slice() }; });
    c.plans.set(q, [{ frames: [{ content: "Admitted non-author partial" }], holdOnly: true }]);
    await f.gate(ctx, "http.admitted-ask-control", async () => { const res = await ctx.request("/api/ask/stream", { cookie: member, method: "POST", body: { question: q, session_id: fx.a.id, project_id: fx.p.id, conversation_memory: fx.a.pre } }); assert.equal(res.status, 200); askText = res.text(); assert.ok(await pollUntil(() => events.join("").includes("Admitted non-author partial"), 10000)); const sent = ctx.upstream.requests.find((r: any) => r.body?.question === q); assert.ok(JSON.stringify(sent.body).includes(instructions)); return { status: res.status, sent, events: events.slice() }; });
    await f.gate(ctx, "http.exact-detach", async () => { const before = state(ctx); await f.json(ctx, `/api/me/projects/${fx.p.id}`, owner, "DELETE"); const after = state(ctx); assertDeleteOnly(before, after, fx.p.id); return { before, after }; });
    await f.gate(ctx, "http.fresh-admission", () => bothAdmissions(ctx, owner, member, fx));
    await f.gate(ctx, "http.open-feed-observation", async () => { const at = events.length, blob = f.blob("author-after-detach"); await f.json(ctx, `/api/me/chats/${fx.a.id}`, owner, "PATCH", { memory: blob }); const committed = state(ctx).sessions.find((s: any) => s.id === fx.a.id); assert.equal(committed.memory, JSON.stringify(blob));
      // ChatEvent.kind is optional: absence means the same settled change.
      const changed = () => events.slice(at).join("").split("\n").filter(line => line.startsWith("data: ")).map(line => JSON.parse(line.slice(6))).some(e => (e.kind === undefined || e.kind === "changed") && e.by === ctx.users.owner.id && e.updatedAt === committed.updated_at);
      assert.ok(await pollUntil(changed, 10000)); return { feedStillAdmitted: true, freshAdmission: 404, postDetachEvents: events.slice(at), authorMemory: blob, committed, note: "observed connect-time subscription; no instantaneous-revocation claim" }; });
    c.release(q, [{ content: " completed after detach" }, { memory_update: late }, f.done]);
    await f.gate(ctx, "http.admitted-ask-completes", async () => { const text = await askText; assert.ok(text?.includes("completed after detach")); assert.ok(text?.includes(JSON.stringify(late))); assert.ok(await pollUntil(() => events.join("").includes('"kind":"turn_done"'), 10000)); return { text, events: events.slice(), note: "admitted ask/relay finishes; that does not authorize a new save" }; });
    await f.gate(ctx, "http.non-author-late-save-rejected", async () => { const before = state(ctx), res = await ctx.request(`/api/me/chats/${fx.a.id}`, { cookie: member, method: "PATCH", body: { messages: fx.a.base, memory: late } }); assert.equal(res.status, 404); await res.json(); assert.deepEqual(state(ctx), before); return { status: res.status, before, after: state(ctx) }; });
    await f.gate(ctx, "http.fresh-general-ask-scope", async () => { const question = `fresh-after-detach-${ctx.label}`; c.plans.set(question, [{ frames: [{ content: "Fresh caller-key answer" }, f.done] }]); const res = await ctx.request("/api/ask/stream", { cookie: member, method: "POST", body: { question, session_id: fx.a.id, project_id: fx.p.id, conversation_memory: fx.a.pre } }); assert.equal(res.status, 200); const text = await res.text(), sent = ctx.upstream.requests.find((r: any) => r.body?.question === question); assert.ok(text.includes("Fresh caller-key answer")); assert.equal(JSON.stringify(sent.body).includes(instructions), false); assert.equal("session_id" in sent.body, false); assert.equal("project_id" in sent.body, false); return { status: res.status, sent, note: "general ask remains caller-key authorized; deleted optional context/relay omitted" }; });
  } finally { stopped = true; abort.abort(); await pump; writeFileSync(join(ctx.workDir, "logs", "remote-http-events.json"), JSON.stringify({ events }, null, 2)); }
}

export async function runRemoteBrowser(ctx: any) {
  const rec = new Recorder(join(ctx.workDir, "logs")), tool = browserPrerequisites(); assert.deepEqual(tool.problems, []);
  const require = createRequire(join(ctx.appDir, "package.json")), pw = require(join(tool.pwPath, "index.js")), owner = new BrowserSession(pw, tool.chromiumPath, ctx.baseUrl, rec), member = new BrowserSession(pw, tool.chromiumPath, ctx.baseUrl, rec), sessions = [owner, member], c = makeUpstreamController(ctx);
  for (const [path, name] of [["src/app/page.tsx", "page.tsx"], ["src/app/api/me/projects/[id]/route.ts", "delete-route.ts"], ["src/app/api/me/chats/[id]/events/route.ts", "feed-route.ts"], ["src/app/api/ask/stream/route.ts", "ask-route.ts"]]) copyFileSync(join(ctx.appDir, path), join(rec.dir, name));
  writeFileSync(join(rec.dir, "tooling.json"), JSON.stringify({ ...tool, version: JSON.parse(readFileSync(join(tool.pwPath, "package.json"), "utf8")).version, tmpdir: process.env.TMPDIR, install: false }, null, 2));
  const writes: any[] = [], acks: any[] = [], asks: any[] = [], reads: any[] = [], dialogs: any[] = [], flows: any[] = []; let deniedPath: string | undefined;
  const g = (id: string, fn: () => Promise<any>) => f.gate(ctx, `browser.${id}`, fn);
  try {
    for (const [s, name] of [[owner, "owner"], [member, "member"]] as const) {
      await s.start(s === member ? owner.browser : undefined);
      await s.context.addInitScript(() => { const Original = window.EventSource; (window as any).__followupFeeds = []; window.EventSource = class extends Original { row: any;
        constructor(url: string | URL, init?: EventSourceInit) { super(url, init); this.row = { url: String(url), ready: 0, closed: false, events: [] }; (window as any).__followupFeeds.push(this.row); this.addEventListener("open", () => this.row.ready = this.readyState); this.addEventListener("error", () => this.row.ready = this.readyState); this.addEventListener("message", e => this.row.events.push(JSON.parse(e.data))); } close() { this.row.closed = true; this.row.ready = 2; super.close(); } }; });
      s.context.on("request", (r: any) => { const path = new URL(r.url()).pathname, method = r.method(); if (path === "/api/ask/stream") asks.push({ name, id: r.headers()["x-request-id"], body: r.postDataJSON(), at: Date.now() }); if (method === "GET" && /^\/api\/me\/chats\/[^/]+$/.test(path)) reads.push({ name, path, at: Date.now() }); if ((method === "DELETE" && /^\/api\/me\/projects\/[^/]+$/.test(path)) || (method === "PATCH" && /^\/api\/me\/chats\/[^/]+$/.test(path))) writes.push({ name, path, method, body: r.postDataJSON(), at: Date.now() }); });
      s.context.on("response", (r: any) => { const path = new URL(r.url()).pathname, method = r.request().method(); if ((method === "DELETE" && /^\/api\/me\/projects\/[^/]+$/.test(path)) || (method === "PATCH" && /^\/api\/me\/chats\/[^/]+$/.test(path))) acks.push({ name, path, method, body: r.request().postDataJSON(), status: r.status(), at: Date.now() }); });
      await s.login(ctx, ctx.users[name].email, ctx.users[name].password);
    }
    const sidebar = async (s: BrowserSession) => { if (!await s.drawer().isVisible()) { await s.page.locator('button[aria-label="Toggle sidebar"], button[aria-label="Seitenleiste umschalten"]').click(); await s.drawer().waitFor({ state: "visible", timeout: 30000 }); } };
    const closeSidebar = async (s: BrowserSession) => { if (await s.drawer().isVisible()) await s.drawer().locator("button").first().click(); };
    const native = async (p: any, decision: "accept" | "dismiss", locale: "en" | "de" = "en") => { await sidebar(owner); const row = owner.drawer().getByText(p.name, { exact: true }).locator(".."); await row.hover(); const handled = new Promise<void>((resolve, reject) => owner.page.once("dialog", async (d: any) => { try { dialogs.push({ project: p.id, locale, decision, type: d.type(), text: d.message() }); assert.equal(d.type(), "confirm"); assert.equal(d.message(), locale === "en" ? "Delete this project? Chats are kept and move back to their authors' chat lists." : "Dieses Projekt löschen? Chats bleiben erhalten und wandern zurück in die Chat-Listen ihrer Autoren."); await d[decision](); resolve(); } catch (e) { await d.dismiss().catch(() => {}); reject(e); } })); await row.locator(`button[title="${locale === "en" ? "Delete project" : "Projekt löschen"}"]`).click(); await handled; };
    const frames = () => member.page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
    const open = async (chat: any) => { await member.page.goto(`${ctx.baseUrl}/?chat=${chat.id}`, { waitUntil: "domcontentloaded" }); await member.waitForComposer(); assert.ok(await f.visible(member, chat.base.at(-1).content)); await f.ready(member, chat.id); };
    const readyUser = async () => assert.ok(await pollUntil(() => member.page.evaluate(() => (window as any).__followupFeeds.some((r: any) => r.url === "/api/me/events" && !r.closed && r.ready === 1)), 15000));
    const ownReads = () => reads.filter(r => r.name === "member").length;
    const waitActive = async (question: string, count: number) => assert.ok(await pollUntil(() => { const browser = asks.filter(a => a.name === "member" && a.body.question === question), upstream = ctx.upstream.requests.filter((r: any) => r.body?.question === question); return browser.length === count && upstream.length === count && browser.at(-1).id === upstream.at(-1).id && ctx.upstream.pending.has(upstream.at(-1).id) && c.held.some(h => h.id === upstream.at(-1).id); }, 15000), "matching active browser/upstream operation required");
    const consume = (question: string, chat: any, projectId: string | null, count: number, prefix = chat.base) => { const raw = asks.filter(a => a.name === "member" && a.body.question === question).at(-1).body, sent = ctx.upstream.requests.filter((r: any) => r.body?.question === question).at(-1).body; assert.equal(raw.project_id, projectId, "remote detach must select personal context without a repairing chat GET"); assert.equal(raw.session_id, chat.id); assert.equal(raw.assistant_id, ctx.ids.soul); assert.deepEqual(raw.conversation_memory, chat.pre); assert.deepEqual(sent.conversation_memory, chat.pre); assert.deepEqual(raw.conversation_history, prefix.map((m: any) => ({ role: m.role, content: m.content }))); assert.equal(JSON.stringify(sent).includes(instructions), projectId !== null); assert.equal(ownReads(), count); return { raw, sent }; };
    const healthy = await fixture(ctx, owner.cookie, member.cookie, "Healthy remote");
    await g("logins-dark-en-de", async () => { for (const [s, name] of [[owner, "owner"], [member, "member"]] as const) { assert.equal((await f.json(ctx, "/api/auth/me", s.cookie)).id, ctx.users[name].id); assert.equal(await s.page.evaluate(() => document.documentElement.classList.contains("dark")), true); } setAppLocale(ctx.dataDir, "de"); await owner.page.reload(); await owner.waitForComposer(); try { const before = state(ctx); await native(healthy.p, "dismiss", "de"); assert.deepEqual(state(ctx), before); await rec.screenshot(owner.page, "remote-dark-de-cancel"); } finally { setAppLocale(ctx.dataDir, "en"); } await owner.page.reload(); await owner.waitForComposer(); return { logins: 2, locales: ["en", "de"] }; });
    await open(healthy.b); await readyUser();
    await g("cancel-control", async () => { const before = state(ctx), n = writes.length; await native(healthy.p, "dismiss"); assert.deepEqual(state(ctx), before); assert.equal(writes.length, n); return before; });
    const hq = healthy.b.base[0].content, hn = ownReads(); c.plans.set(hq, [{ frames: [{ content: "Healthy member redo" }], holdOnly: true }]); await member.clickRegenerate(); await waitActive(hq, 1);
    await g("healthy-consumer", async () => consume(hq, healthy.b, healthy.p.id, hn, [])); c.release(hq, [{ memory_update: f.blob("healthy-final") }, f.done]);
    await g("healthy-settles", () => f.durable(member, ctx, healthy.b.id, f.blob("healthy-final"), "Healthy member redo"));
    for (const kind of ["regenerate", "edit"] as const) {
      const fx = await fixture(ctx, owner.cookie, member.cookie, `Remote ${kind}`); await owner.page.reload(); await owner.waitForComposer(); await open(fx.b); await readyUser();
      const q = `remote-${kind}-${ctx.label}`, answer = `Remote ${kind} completed answer`, late = f.blob(`${kind}-author-late`); c.plans.set(q, [{ frames: [{ content: answer }, f.done], holdMemoryBlob: late }, { frames: [{ content: "Remote regenerate redo" }], holdOnly: true }]);
      await member.send(q); await member.waitAnswerVisible(answer); const origin = (await f.durable(member, ctx, fx.b.id, fx.b.pre, answer)).http.body.messages;
      await g(`${kind}-origin-control`, async () => { await waitActive(q, 1); await f.ready(member, fx.b.id); assert.equal(new URL(member.page.url()).searchParams.get("chat"), fx.b.id); return { origin, atSend: fx.b.pre, selected: fx.b.id }; });
      await g(`${kind}-exact-detach`, async () => { const before = state(ctx); await native(fx.p, "accept"); assert.ok(await pollUntil(() => acks.some(a => a.method === "DELETE" && a.path === `/api/me/projects/${fx.p.id}` && a.status === 200), 10000)); const after = state(ctx); assertDeleteOnly(before, after, fx.p.id); flows.push({ kind, project: fx.p.id, chat: fx.b.id, before, after }); return { before, after }; });
      await g(`${kind}-flat-selected`, async () => { await sidebar(member); assert.ok(await pollUntil(async () => await member.drawer().getByText(fx.p.name, { exact: true }).count() === 0 && await member.drawer().getByText(fx.b.title, { exact: true }).count() === 1, 10000)); assert.equal(await member.drawer().getByText(fx.a.title, { exact: true }).count(), 0); assert.equal(new URL(member.page.url()).searchParams.get("chat"), fx.b.id); assert.ok(await f.visible(member, answer)); const rows = (await f.json(ctx, "/api/me/chats", member.cookie)).sessions; assert.equal(rows.filter((r: any) => r.id === fx.b.id).length, 1); assert.equal(rows.some((r: any) => r.id === fx.a.id), false); await rec.screenshot(member.page, `remote-${kind}-detached-selected`); await closeSidebar(member); await frames(); return { rows, selected: fx.b.id }; });
      await g(`${kind}-fresh-admission`, () => bothAdmissions(ctx, owner.cookie, member.cookie, fx)); c.release(q, [{ memory_update: late }]);
      await g(`${kind}-late-memory`, async () => { const got = await f.durable(member, ctx, fx.b.id, late, answer); assert.equal(got.http.body.projectId, null); assert.equal(got.http.body.assistantId, ctx.ids.soul); assert.deepEqual(f.projection(got.http.body.messages), f.projection(origin)); return got; });
      await g(`${kind}-direct-feedback`, async () => { const before = writes.length, count = ownReads(), got = await f.feedback(member, ctx, fx.b.id, origin, late, answer); assert.ok(writes.length > before); assert.equal(ownReads(), count); const raw = state(ctx).messages.find((m: any) => m.id === origin.at(-1).id); assert.equal(JSON.parse(raw.metadata).feedback, "down"); return got; });
      const question = kind === "edit" ? `remote-edit-redo-${ctx.label}` : q, count = ownReads(); if (kind === "edit") { c.plans.set(question, [{ frames: [{ content: "Remote edit redo" }], holdOnly: true }]); await member.editLastMessage(q, question); } else await member.clickRegenerate(); await waitActive(question, kind === "edit" ? 1 : 2);
      await g(`${kind}-direct-snapshot-context`, async () => consume(question, fx.b, null, count)); c.release(question, [{ memory_update: f.blob(`${kind}-redo-final`) }, f.done]);
      await g(`${kind}-settles`, async () => { const got = await f.durable(member, ctx, fx.b.id, f.blob(`${kind}-redo-final`), `Remote ${kind} redo`); assert.equal(got.http.body.projectId, null); assert.equal(got.http.body.assistantId, ctx.ids.soul); assert.deepEqual(f.projection(got.http.body.messages).slice(0, fx.b.base.length), f.projection(fx.b.base)); await rec.screenshot(member.page, `remote-${kind}-settled`); return got; });
    }
    const fx = await fixture(ctx, owner.cookie, member.cookie, "Non-author remote"); await owner.page.reload(); await owner.waitForComposer(); await open(fx.a); await readyUser();
    const q = `non-author-browser-${ctx.label}`, late = f.blob("non-author-browser-late"); c.plans.set(q, [{ frames: [{ content: "Non-author admitted partial" }], holdOnly: true }]); await member.send(q);
    await g("non-author-selected-control", async () => { await waitActive(q, 1); assert.ok(await f.visible(member, "Non-author admitted partial")); assert.equal(new URL(member.page.url()).searchParams.get("chat"), fx.a.id); const got = await f.json(ctx, `/api/me/chats/${fx.a.id}`, member.cookie); return { got, upstream: ctx.upstream.requests.find((r: any) => r.body?.question === q) }; });
    let detached: any;
    await g("non-author-detach", async () => { const before = state(ctx); await native(fx.p, "accept"); assert.ok(await pollUntil(() => acks.some(a => a.path === `/api/me/projects/${fx.p.id}` && a.status === 200), 10000)); detached = state(ctx); assertDeleteOnly(before, detached, fx.p.id); return { before, after: detached }; });
    await g("non-author-fresh-rejection", () => admission(ctx, member.cookie, fx.a.id, false)); deniedPath = `/api/me/chats/${fx.a.id}`;
    c.release(q, [{ content: " completed after detach" }, { memory_update: late }, f.done]);
    await g("non-author-admitted-completion", async () => { assert.ok(await f.visible(member, "Non-author admitted partial completed after detach")); assert.ok(await pollUntil(() => asks.filter(a => a.body.question === q).length === 1 && acks.some(a => a.path === deniedPath && a.status === 404), 10000)); const sent = ctx.upstream.requests.find((r: any) => r.body?.question === q); assert.ok(JSON.stringify(sent.body).includes(instructions)); return { sent, answer: "Non-author admitted partial completed after detach", note: "operation accepted before deletion completes; persistence has fresh authority" }; });
    await g("non-author-save-rejection", async () => { const rejected = acks.filter(a => a.path === deniedPath && a.status === 404); assert.equal(rejected.length, 1); assert.deepEqual(rejected[0].body.memory, late); assert.equal(rejected[0].body.messages.at(-1).content, "Non-author admitted partial completed after detach"); assert.deepEqual(state(ctx), detached); return { attemptedSave: rejected, unchanged: state(ctx) }; });
    await pollUntil(() => writes.length === acks.length, 10000);
    await g("operation-outcomes", async () => { assert.equal(writes.length, acks.length); const rejected = acks.filter(a => a.status !== 200); assert.equal(rejected.length, 1); assert.equal(rejected[0].name, "member"); assert.equal(rejected[0].method, "PATCH"); assert.equal(rejected[0].path, deniedPath); assert.equal(rejected[0].status, 404); for (const a of acks) assert.ok(writes.some(w => w.name === a.name && w.path === a.path && w.method === a.method && JSON.stringify(w.body) === JSON.stringify(a.body))); return { writes, acknowledgments: acks, expectedRejection: rejected }; });
  } finally {
    ctx.check("browser.no-page-errors", sessions.every(s => !s.pageErrors.length), sessions.map(s => s.pageErrors)); ctx.check("browser.no-blocked-requests", sessions.every(s => !s.blocked.length), sessions.map(s => s.blocked)); ctx.check("browser.responses-drained", !c.held.length && !c.unmatched.length && !ctx.upstream.pending.size, { held: c.held, unmatched: c.unmatched });
    writeFileSync(join(rec.dir, "remote-observations.json"), JSON.stringify({ dialogs, writes, acknowledgments: acks, expectedRejectedPath: deniedPath, asks, reads, flows, observations: rec.observations, patches: rec.patches }, null, 2)); await member.close(); await owner.close();
  }
}
