// association-list-v1: genuine older personal-list bytes delivered after current
// association/view changes. Consumer values are independent of refresh counts.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BrowserSession, Recorder, browserPrerequisites, makeUpstreamController, pollUntil, setAppLocale } from "./chat-browser-checks";
import { projectFixture as f } from "./chat-project-followup-checks";
import { assertMoveOnly } from "./chat-project-move-checks";
import { assertDeleteOnly } from "./chat-project-delete-checks";

export const ASSOCIATION_GATES = ["browser.login-dark-en-de", "browser.healthy-move", "browser.healthy-context", "browser.healthy-settles", "browser.healthy-remote-delete", "browser.healthy-detached-context", "browser.healthy-detached-settles",
  ...["move", "navigation"].flatMap(k => [`browser.${k}-held-list-control`, `browser.${k}-association-control`, `browser.${k}-delivery-control`, `browser.${k}-late-compaction`, `browser.${k}-direct-feedback`, `browser.${k}-direct-context-snapshot`, `browser.${k}-settles`]),
  "browser.acknowledgments", "browser.no-page-errors", "browser.no-blocked-requests", "browser.responses-drained"];
const instructions = "Synthetic association-list project context.";
function state(ctx: any, id?: string) {
  const require = createRequire(join(ctx.appDir, "package.json")), Database = require("better-sqlite3"), db = new Database(join(ctx.dataDir, "cortex-chat.db"), { readonly: true, fileMustExist: true });
  try { return id ? { session: db.prepare("SELECT * FROM chat_sessions WHERE id = ?").get(id), messages: db.prepare("SELECT * FROM chat_messages WHERE chat_session_id = ? ORDER BY created_at,rowid").all(id) } : { projects: db.prepare("SELECT * FROM projects ORDER BY id").all(), shares: db.prepare("SELECT * FROM project_shares ORDER BY id").all(), sessions: db.prepare("SELECT * FROM chat_sessions ORDER BY id").all(), messages: db.prepare("SELECT * FROM chat_messages ORDER BY id").all() }; } finally { db.close(); }
}
async function fixture(ctx: any, owner: string, member: string, tag: string) {
  const p = (await f.json(ctx, "/api/me/projects", member, "POST", { name: `${tag} shared target`, instructions })).project;
  await f.json(ctx, `/api/me/projects/${p.id}/shares`, member, "PUT", { shares: [{ userId: ctx.users.owner.id }] });
  const create = async (title: string, projectId?: string) => { const id = (await f.json(ctx, "/api/me/chats", owner, "POST", { title, projectId, assistantId: ctx.ids.soul })).id, pre = f.blob(`${title}-pre`), base = f.pair(`fx-association-${title}-${ctx.label}`, title).map(m => m.role === "assistant" ? { ...m, feedback: "up", thinking: ["Retained reasoning"], sources: [{ document_id: "fx-association-source", chunk_id: "fx-association-chunk", sid: "fx-association-stable-sid", content: "Retained source", score: 0.42, metadata: { filename: "association-fixture.md" } }] } : m); await f.patch(ctx, owner, id, base, pre); return { id, title, pre, base }; };
  return { p, source: await create(`${tag} source`), other: await create(`${tag} other`), signal: await create(`${tag} signal`, p.id) };
}
export async function runAssociationBrowser(ctx: any) {
  const rec = new Recorder(join(ctx.workDir, "logs")), tool = browserPrerequisites(); assert.deepEqual(tool.problems, []);
  const require = createRequire(join(ctx.appDir, "package.json")), pw = require(join(tool.pwPath, "index.js")), owner = new BrowserSession(pw, tool.chromiumPath, ctx.baseUrl, rec), c = makeUpstreamController(ctx);
  copyFileSync(join(ctx.appDir, "src/app/page.tsx"), join(rec.dir, "page.tsx")); writeFileSync(join(rec.dir, "tooling.json"), JSON.stringify({ ...tool, version: JSON.parse(readFileSync(join(tool.pwPath, "package.json"), "utf8")).version, tmpdir: process.env.TMPDIR, install: false }, null, 2));
  const writes: any[] = [], acks: any[] = [], asks: any[] = [], reads: any[] = [], barriers: any[] = [], dialogs: any[] = [], schedules: any[] = []; let listRequests = 0, listResponses = 0;
  const g = (id: string, fn: () => Promise<any>) => f.gate(ctx, `browser.${id}`, fn);
  try {
    await owner.start(); await owner.context.addInitScript(() => { const Original = window.EventSource; (window as any).__followupFeeds = []; window.EventSource = class extends Original { row: any;
      constructor(url: string | URL, init?: EventSourceInit) { super(url, init); this.row = { url: String(url), ready: 0, closed: false }; (window as any).__followupFeeds.push(this.row); this.addEventListener("open", () => this.row.ready = this.readyState); this.addEventListener("error", () => this.row.ready = this.readyState); } close() { this.row.closed = true; this.row.ready = 2; super.close(); } }; });
    owner.context.on("request", (r: any) => { const path = new URL(r.url()).pathname, method = r.method(); if (method === "GET" && path === "/api/me/chats") listRequests++; if (method === "GET" && /^\/api\/me\/chats\/[^/]+$/.test(path)) reads.push({ path, at: Date.now() }); if (method === "PATCH" && /^\/api\/me\/chats\/[^/]+$/.test(path)) writes.push({ path, body: r.postDataJSON(), at: Date.now() }); if (path === "/api/ask/stream") asks.push({ id: r.headers()["x-request-id"], body: r.postDataJSON(), at: Date.now() }); });
    owner.context.on("response", (r: any) => { const path = new URL(r.url()).pathname, method = r.request().method(); if (method === "GET" && path === "/api/me/chats") listResponses++; if (method === "PATCH" && /^\/api\/me\/chats\/[^/]+$/.test(path)) acks.push({ path, body: r.request().postDataJSON(), status: r.status(), at: Date.now() }); });
    await owner.login(ctx, ctx.users.owner.email, ctx.users.owner.password); const member = await f.login(ctx, "member");
    const frames = () => owner.page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
    const quiet = async () => { assert.ok(await pollUntil(() => listRequests === listResponses && writes.length === acks.length, 10000)); await frames(); };
    const sidebar = async () => { if (!await owner.drawer().isVisible()) { await owner.page.locator('button[aria-label="Toggle sidebar"], button[aria-label="Seitenleiste umschalten"]').click(); await owner.drawer().waitFor({ state: "visible", timeout: 30000 }); } };
    const closeSidebar = async () => { if (await owner.drawer().isVisible()) await owner.drawer().locator("button").first().click(); };
    const row = (text: string) => owner.drawer().getByText(text, { exact: true }).locator("..");
    const open = async (chat: any) => { await owner.page.goto(`${ctx.baseUrl}/?chat=${chat.id}`, { waitUntil: "domcontentloaded" }); await owner.waitForComposer(); assert.ok(await f.visible(owner, chat.base.at(-1).content)); await quiet(); };
    const select = async (chat: any) => { await sidebar(); await row(chat.title).click(); assert.ok(await pollUntil(() => new URL(owner.page.url()).searchParams.get("chat") === chat.id, 10000)); assert.ok(await f.visible(owner, chat.base[1].content)); await closeSidebar(); await frames(); };
    const drag = async (chat: any, p: any) => { await sidebar(); const handled = new Promise<void>((resolve, reject) => owner.page.once("dialog", async (d: any) => { try { assert.equal(d.type(), "confirm"); assert.equal(d.message(), "This project is shared — all members will be able to read this chat's entire history and continue the conversation. Move it?"); dialogs.push({ type: d.type(), text: d.message(), chat: chat.id, project: p.id }); await d.accept(); resolve(); } catch (e) { await d.dismiss().catch(() => {}); reject(e); } })); await row(chat.title).dragTo(row(p.name)); await handled; assert.ok(await pollUntil(() => acks.some(a => a.path === `/api/me/chats/${chat.id}` && a.body.projectId === p.id && a.status === 200), 10000)); await closeSidebar(); await frames(); };
    const readyUser = async () => assert.ok(await pollUntil(() => owner.page.evaluate(() => (window as any).__followupFeeds.some((r: any) => r.url === "/api/me/events" && !r.closed && r.ready === 1)), 15000));
    const waitActive = async (q: string, count: number) => assert.ok(await pollUntil(() => { const b = asks.filter(a => a.body.question === q), u = ctx.upstream.requests.filter((r: any) => r.body?.question === q); return b.length === count && u.length === count && b.at(-1).id === u.at(-1).id && ctx.upstream.pending.has(u.at(-1).id) && c.held.some(h => h.id === u.at(-1).id); }, 15000));
    const consume = (q: string, chat: any, projectId: string | null, count: number, prefix = chat.base) => { const raw = asks.filter(a => a.body.question === q).at(-1).body, sent = ctx.upstream.requests.filter((r: any) => r.body?.question === q).at(-1).body; assert.equal(raw.session_id, chat.id); assert.deepEqual(raw.conversation_memory, chat.pre); assert.deepEqual(sent.conversation_memory, chat.pre); assert.equal(raw.assistant_id, ctx.ids.soul); assert.deepEqual(raw.conversation_history, prefix.map((m: any) => ({ role: m.role, content: m.content }))); assert.equal(reads.length, count, "direct consumer must not repair through chat GET"); assert.equal(raw.project_id, projectId, "older list must not clear current acknowledged/loaded project context"); assert.equal(JSON.stringify(sent).includes(instructions), projectId !== null); return { raw, sent }; };
    const origin = async (chat: any, tag: string) => { const q = `association-${tag}-${ctx.label}`, answer = `${tag} completed origin`, late = f.blob(`${tag}-late`); c.plans.set(q, [{ frames: [{ content: answer }, f.done], holdMemoryBlob: late }, { frames: [{ content: `${tag} direct redo` }], holdOnly: true }]); await owner.send(q); await owner.waitAnswerVisible(answer); const history = (await f.durable(owner, ctx, chat.id, chat.pre, answer)).http.body.messages; await waitActive(q, 1); await quiet(); return { q, answer, late, history }; };
    const holdList = async () => { const rows: any[] = [], matcher = `${ctx.baseUrl}/api/me/chats`; const handler = async (route: any) => { if (route.request().method() !== "GET") return route.fallback(); const entry: any = { sequence: rows.length + 1, requestedAt: Date.now(), delivered: false }; rows.push(entry); const response = await route.fetch(); entry.status = response.status(); entry.body = await response.json(); if (entry.sequence === 1) { let release!: () => void; const promise = new Promise<void>(r => release = r); entry.release = release; await promise; } await route.fulfill({ response }); entry.delivered = true; entry.deliveredAt = Date.now(); }; await owner.context.route(matcher, handler); const h = { rows, close: async () => { for (const r of rows) r.release?.(); await owner.context.unroute(matcher, handler); } }; barriers.push(h); return h; };
    const trigger = async (fx: any, tag: string) => { await readyUser(); await f.json(ctx, `/api/me/chats/${fx.signal.id}`, member, "PATCH", { messages: fx.signal.base, memory: f.blob(tag) }); };

    await g("login-dark-en-de", async () => { assert.equal((await f.json(ctx, "/api/auth/me", owner.cookie)).id, ctx.users.owner.id); assert.equal(await owner.page.evaluate(() => document.documentElement.classList.contains("dark")), true); setAppLocale(ctx.dataDir, "de"); try { await owner.page.reload(); await owner.waitForComposer(); assert.equal(await owner.composer().getAttribute("placeholder"), "Stelle eine komplexe Frage für Deep Research..."); await rec.screenshot(owner.page, "association-dark-de"); } finally { setAppLocale(ctx.dataDir, "en"); } await owner.page.reload(); await owner.waitForComposer(); return { locales: ["de", "en"], form: true }; });
    const healthy = await fixture(ctx, owner.cookie, member, "Healthy association"); await open(healthy.source);
    await g("healthy-move", async () => { const before = state(ctx, healthy.source.id); await drag(healthy.source, healthy.p); assertMoveOnly(before, state(ctx, healthy.source.id), healthy.p.id); await f.ready(owner, healthy.source.id); await quiet(); return { before, after: state(ctx, healthy.source.id) }; });
    const hq = healthy.source.base[0].content, hn = reads.length; c.plans.set(hq, [{ frames: [{ content: "Healthy association redo" }], holdOnly: true }]); await owner.clickRegenerate(); await waitActive(hq, 1);
    await g("healthy-context", async () => consume(hq, healthy.source, healthy.p.id, hn, [])); c.release(hq, [{ memory_update: f.blob("healthy-association-final") }, f.done]); await g("healthy-settles", () => f.durable(owner, ctx, healthy.source.id, f.blob("healthy-association-final"), "Healthy association redo"));
    await g("healthy-remote-delete", async () => { await readyUser(); const before = state(ctx); await f.json(ctx, `/api/me/projects/${healthy.p.id}`, member, "DELETE"); assertDeleteOnly(before, state(ctx), healthy.p.id); await sidebar(); assert.ok(await pollUntil(() => owner.drawer().getByText(healthy.p.name, { exact: true }).count().then((n: number) => n === 0), 10000)); await closeSidebar(); await quiet(); return { before, after: state(ctx) }; });
    const hd = reads.length; c.plans.set(hq, [{ frames: [{ content: "Healthy detached redo" }], holdOnly: true }]); await owner.clickRegenerate(); await waitActive(hq, 2);
    await g("healthy-detached-context", async () => consume(hq, healthy.source, null, hd, [])); c.release(hq, [{ memory_update: f.blob("healthy-detached-final") }, f.done]); await g("healthy-detached-settles", () => f.durable(owner, ctx, healthy.source.id, f.blob("healthy-detached-final"), "Healthy detached redo"));

    for (const kind of ["move", "navigation"] as const) {
      const fx = await fixture(ctx, owner.cookie, member, `Delayed ${kind}`); await open(kind === "move" ? fx.source : fx.other); const selected = kind === "move" ? fx.source : fx.other, turn = await origin(selected, kind);
      if (kind === "navigation") await select(fx.source);
      await quiet(); const holder = await holdList(); await trigger(fx, `${kind}-refresh-signal`);
      assert.ok(await pollUntil(() => holder.rows[0]?.body, 10000));
      await g(`${kind}-held-list-control`, async () => { assert.equal(holder.rows[0].status, 200); assert.equal(holder.rows[0].delivered, false); assert.ok(holder.rows[0].body.sessions.some((s: any) => s.id === selected.id)); assert.equal(state(ctx, selected.id).session.project_id, null); return { captured: holder.rows[0].body, sequence: holder.rows[0].sequence, selectedAtDispatch: new URL(owner.page.url()).searchParams.get("chat") }; });
      await g(`${kind}-association-control`, async () => { const before = state(ctx, selected.id); if (kind === "move") { await drag(selected, fx.p); await f.ready(owner, selected.id); assert.ok(await pollUntil(() => holder.rows.slice(1).some(r => r.delivered && r.status === 200 && !r.body.sessions.some((s: any) => s.id === selected.id)), 10000)); } else { await f.json(ctx, `/api/me/chats/${selected.id}`, owner.cookie, "PATCH", { projectId: fx.p.id }); await select(selected); await f.ready(owner, selected.id); assert.equal(holder.rows.length, 1, "navigation case leaves the older list as latest requested; view ownership must protect selection"); } assertMoveOnly(before, state(ctx, selected.id), fx.p.id); assert.equal(new URL(owner.page.url()).searchParams.get("chat"), selected.id); return { before, after: state(ctx, selected.id), source: kind === "move" ? "acknowledged UI move/newer list" : "fresh selected GET after acknowledged author move", newerLists: holder.rows.slice(1).map(r => r.body) }; });
      holder.rows[0].release(); assert.ok(await pollUntil(() => holder.rows[0].delivered, 5000)); await frames();
      await g(`${kind}-delivery-control`, async () => { const observation = { kind, old: holder.rows[0].body, selected: new URL(owner.page.url()).searchParams.get("chat"), current: state(ctx, selected.id), reads: reads.slice(), lists: holder.rows.map(({ release, ...r }) => r) }; assert.equal(observation.selected, selected.id); assert.equal(observation.current.session.project_id, fx.p.id); schedules.push(observation); return observation; });
      c.release(turn.q, [{ memory_update: turn.late }]); await g(`${kind}-late-compaction`, async () => { const got = await f.durable(owner, ctx, selected.id, turn.late, turn.answer); assert.equal(got.http.body.projectId, fx.p.id); assert.deepEqual(f.projection(got.http.body.messages), f.projection(turn.history)); return got; }); await quiet();
      await g(`${kind}-direct-feedback`, async () => { const n = reads.length, before = writes.length, got = await f.feedback(owner, ctx, selected.id, turn.history, turn.late, turn.answer); assert.ok(writes.length > before); assert.equal(reads.length, n); return got; }); await quiet();
      const q = kind === "navigation" ? `association-navigation-edit-${ctx.label}` : turn.q, n = reads.length;
      if (kind === "navigation") { c.plans.set(q, [{ frames: [{ content: "navigation direct redo" }], holdOnly: true }]); await owner.editLastMessage(turn.q, q); } else await owner.clickRegenerate(); await waitActive(q, kind === "move" ? 2 : 1);
      await g(`${kind}-direct-context-snapshot`, async () => consume(q, selected, fx.p.id, n)); c.release(q, [{ memory_update: f.blob(`${kind}-redo-final`) }, f.done]); await g(`${kind}-settles`, async () => { const got = await f.durable(owner, ctx, selected.id, f.blob(`${kind}-redo-final`), `${kind} direct redo`); assert.equal(got.http.body.projectId, fx.p.id); await rec.screenshot(owner.page, `association-${kind}-settled`); return got; }); await holder.close();
    }
    await pollUntil(() => writes.length === acks.length, 10000); await g("acknowledgments", async () => { assert.equal(writes.length, acks.length); assert.ok(acks.every(a => a.status === 200)); for (const a of acks) assert.ok(writes.some(w => w.path === a.path && JSON.stringify(w.body) === JSON.stringify(a.body))); return { writes, acknowledgments: acks }; });
  } finally {
    for (const h of barriers) await h.close(); ctx.check("browser.no-page-errors", !owner.pageErrors.length, owner.pageErrors); ctx.check("browser.no-blocked-requests", !owner.blocked.length, owner.blocked); ctx.check("browser.responses-drained", !c.held.length && !c.unmatched.length && !ctx.upstream.pending.size && barriers.every(h => h.rows.every((r: any) => r.delivered)), { held: c.held, unmatched: c.unmatched });
    writeFileSync(join(rec.dir, "association-observations.json"), JSON.stringify({ writes, acknowledgments: acks, asks, reads, dialogs, schedules, lists: barriers.map(h => h.rows.map(({ release, ...r }: any) => r)), observations: rec.observations }, null, 2)); await owner.close();
  }
}
