import { withChatRuntime } from "./chat-journey-runtime.mjs";
import { OVERLAP_GATES, runOverlapBrowser } from "./chat-project-move-overlap-checks";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync, copyFileSync, mkdirSync } from "node:fs";
async function main() {
  const [output, label] = process.argv.slice(2); if (!output || !label || process.argv.length !== 4) throw new Error("usage: node --import tsx scripts/chat-project-move-overlap-journey.ts <fresh-output> <fresh-id>");
  const unhandled: string[] = []; process.on("unhandledRejection", e => { unhandled.push(String(e)); process.exitCode = 1; });
  const scripts = dirname(fileURLToPath(import.meta.url)), inputs = ["chat-project-move-overlap-journey.ts", "chat-project-move-overlap-checks.ts", "chat-project-move-checks.ts", "chat-project-followup-checks.ts", "chat-browser-checks.ts", "chat-feed-transport.ts", "chat-journey-runtime.mjs", "tsconfig.chat-project-move-overlap.json"], required = [...OVERLAP_GATES, "runtime.no-unhandled-rejections"];
  const result: any = await withChatRuntime(async (ctx: any) => { mkdirSync(join(ctx.workDir, "logs", "gate-snapshot"), { recursive: true }); for (const file of inputs) copyFileSync(join(scripts, file), join(ctx.workDir, "logs", "gate-snapshot", file)); try { await runOverlapBrowser(ctx); } finally { ctx.check("runtime.no-unhandled-rejections", !unhandled.length, unhandled); ctx.check("runtime.required-selection", required.every(id => ctx.checks.filter((c: any) => c.id === id).length === 1), { required }); } }, { outputDir: resolve(output), label, requestTimeoutMs: 60000, scenarioInputs: inputs.map(f => join(scripts, f)) });
  if (unhandled.length) { result.ok = false; result.errors.push(...unhandled); }
  const verdicts = { gateVersion: "project-move-overlap-v1.1", evaluationExecution: result.ok ? "passed" : "failed", browserJourney: result.ok ? "passed" : "not-accepted", httpJourney: "not-run: the overlap delivery schedule (held response A, second commit B, late A acknowledgment) is browser-delivery-specific; HTTP/SQLite state and acknowledgments are observed inside the browser journey", obligations: Object.fromEntries(required.map(id => [id, result.checks.find((c: any) => c.id === id)?.ok === false ? "failed" : result.ok ? "passed" : "not-accepted"])), scopeGuards: { lww: "both move transactions are accepted and each remains accepted; the final association is the observed outcome of the actual commit order under unchanged atomic full-snapshot LWW", noOwnershipInvention: "the gate asserts observed state/order only; no latest-start-wins, CAS, stale-write rejection or merged-history rule is specified or implied", coverage: "one own chat, two shared targets, one overlap schedule plus single-move/cancel/dark/acknowledgment-after-navigation controls; broader list schedules, unavailable reconciliation and multi-replica remain separate" } };
  if (result.evidence) { result.evidence.claimsSupported.push("actual Chromium two-overlapping-move schedule: commit A held after authoritative commit, second native move commit B with real 200 acknowledgment, A acknowledgment delivered last, direct non-repairing consumers, valid held late compaction, single-move/cancel/dark/navigation controls (see verdicts)"); result.evidence.claimsNotSupported = result.evidence.claimsNotSupported.filter((s: string) => s !== "browser journeys"); }
  if (!result.cleanup?.artifactsCopiedTo) throw new Error("receipt not retained"); writeFileSync(join(result.cleanup.artifactsCopiedTo, "results.json"), JSON.stringify(result, null, 2)); writeFileSync(join(result.cleanup.artifactsCopiedTo, "claim-verdicts.json"), JSON.stringify(verdicts, null, 2)); process.stdout.write(JSON.stringify({ ok: result.ok, verdicts, selected: result.checks.length, passed: result.checks.filter((c: any) => c.ok).length, failures: result.checks.filter((c: any) => !c.ok), errors: result.errors, cleanup: result.cleanup }, null, 2) + "\n"); process.exitCode = result.ok ? 0 : 1;
}
main().catch(e => { process.stderr.write(String(e.stack ?? e) + "\n"); process.exitCode = 1; });
