import { withChatRuntime } from "./chat-journey-runtime.mjs";
import { LOSS_GATES, runLossBrowser } from "./chat-project-delete-response-loss-checks";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync, copyFileSync, mkdirSync } from "node:fs";
async function main() {
  const [output, label] = process.argv.slice(2); if (!output || !label || process.argv.length !== 4) throw new Error("usage: node --import tsx scripts/chat-project-delete-response-loss-journey.ts <fresh-output> <fresh-id>");
  const unhandled: string[] = []; process.on("unhandledRejection", e => { unhandled.push(String(e)); process.exitCode = 1; });
  const scripts = dirname(fileURLToPath(import.meta.url)), inputs = ["chat-project-delete-response-loss-journey.ts", "chat-project-delete-response-loss-checks.ts", "chat-project-delete-checks.ts", "chat-project-followup-checks.ts", "chat-browser-checks.ts", "chat-feed-transport.ts", "chat-journey-runtime.mjs", "tsconfig.chat-project-delete-response-loss.json"], required = [...LOSS_GATES, "runtime.no-unhandled-rejections"];
  const result: any = await withChatRuntime(async (ctx: any) => { mkdirSync(join(ctx.workDir, "logs", "gate-snapshot"), { recursive: true }); for (const file of inputs) copyFileSync(join(scripts, file), join(ctx.workDir, "logs", "gate-snapshot", file)); try { await runLossBrowser(ctx); } finally { ctx.check("runtime.no-unhandled-rejections", !unhandled.length, unhandled); ctx.check("runtime.required-selection", required.every(id => ctx.checks.filter((c: any) => c.id === id).length === 1), { required }); } }, { outputDir: resolve(output), label, requestTimeoutMs: 60000, scenarioInputs: inputs.map(f => join(scripts, f)) });
  if (unhandled.length) { result.ok = false; result.errors.push(...unhandled); }
  const verdicts = { gateVersion: "project-delete-response-loss-v1", evaluationExecution: result.ok ? "passed" : "failed", browserJourney: result.ok ? "passed" : "not-accepted", httpJourney: "not-run: caller-delivery fault is Chromium-specific; inherited delete/remote HTTP gates remain separate", obligations: Object.fromEntries(required.map(id => [id, result.checks.find((c: any) => c.id === id)?.ok === false ? "failed" : result.ok ? "passed" : "not-accepted"])), faultScope: "real successful DELETE captured after commit; browser response aborted; not a rollback, a pre-dispatch failure, or coverage of every unknown dispatch outcome" };
  if (result.evidence) { result.evidence.claimsSupported.push("actual Chromium post-commit DELETE response loss/reconciliation/late compaction/direct immutable consumers with pre-dispatch and success controls (see verdicts)"); result.evidence.claimsNotSupported = result.evidence.claimsNotSupported.filter((s: string) => s !== "browser journeys"); }
  if (!result.cleanup?.artifactsCopiedTo) throw new Error("receipt not retained"); writeFileSync(join(result.cleanup.artifactsCopiedTo, "results.json"), JSON.stringify(result, null, 2)); writeFileSync(join(result.cleanup.artifactsCopiedTo, "claim-verdicts.json"), JSON.stringify(verdicts, null, 2)); process.stdout.write(JSON.stringify({ ok: result.ok, verdicts, selected: result.checks.length, passed: result.checks.filter((c: any) => c.ok).length, failures: result.checks.filter((c: any) => !c.ok), errors: result.errors, cleanup: result.cleanup }, null, 2) + "\n"); process.exitCode = result.ok ? 0 : 1;
}
main().catch(e => { process.stderr.write(String(e.stack ?? e) + "\n"); process.exitCode = 1; });
